#!/bin/sh

# ytmenu
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Project repository: https://github.com/demonkingswarn/ytmenu

VERSION="1.4"

YOUTUBE_URL="https://youtube.com"
INVIDIOUS_URL="https://vid.puffyan.us"

menu() {
	printf "1. Download a video\n"
	printf "2. Search web\n"
}

search() {
	query=$(printf '%s' "$*" | fzf | tr ' ' '+')
	url="$YOUTUBE_URL/$(curl -s "$INVIDIOUS_URL/search?q=$query" | grep -Eo "watch\?v=.{11}" | head -n 1)"
	mpv "$url"
}

download() {
	query=$(printf '%s' "$*" | fzf | tr ' ' '+')
	url="$YOUTUBE_URL/$(curl -s "$INVIDIOUS_URL/search?q=$query" | grep -Eo "watch\?v=.{11}" | head -n 1)"
	youtube-dl "$url"
}

choice=$(menu | fzf | cut -d. -f1) || exit

case $choice in
	1)
		download
		;;
	2)
		search
		;;
	*)
		echo "Program terminated" && exit 0
		;;
esac

