#!/bin/sh

# ytmenu
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Project repository: https://github.com/demonkingswarn/ytmenu

VERSION="1.4.2"

YOUTUBE_URL="https://youtube.com"
INVIDIOUS_URL="https://vid.puffyan.us"

player_fn="mpv"

# Allow the user to customize the defaults
[ -e "$HOME/.config/ytmenurc" ] && . "$HOME/.config/ytmenurc"

menu() {
	printf "1. Download a video\n"
	printf "2. Search web\n"
	printf "3. Update script\n"
}

help_text() {
	while IFS= read -r line; do
		printf "%s\n" "$line"
	done <<-EOF

	Usage:
	  ${0##*/} [-c]
	  ${0##*/} [-v]
	  ${0##*/} -h | -U | -V

	Options:
	-h show helptext
	-v use VLC as the media player
	-U fetch update from github
	-V print version number and exit
	-c shows the selection screen
	EOF
}

version_text() {
	inf "Version: $VERSION" >&2
}

die() {
	err "$*"
	exit 1
}

err() {
	printf "\033[1;31m%s\033[0m\n" "$*" >&2
}

inf() {
	printf "\033[1;32m%s \033[1;35m%s\033[0m\n" "$1" "$2"
}

input() {
	printf "Search YouTube: " ; read query
}

update_script() {
	#Get the newest version of the script
	update="$(curl -sL "https://raw.githubusercontent.com/DemonKingSwarn/ytmenu/main/ytmenu" | diff -u "$0" -)"
	if [ -z "$update" ]; then
		inf "Script is up to date :)"
	else
		if printf '%s\n' "$update" | patch "$0" - ; then
			inf "Script has been updated"
		else
			inf "Can't update for some reason!"
		fi
	fi
}

dep_ch() {
	for dep; do
		if ! command -v "$dep" > /dev/null ; then
			err "Program \"$dep\" not found. Please install it.\n"
			[ "$dep" = "yt-dlp" ] && err "To install yt-dlp, Type pip install yt-dlp"
			die
		fi
	done
}

search_yt() {
	input
	search=$(echo "${query}" | sed 's/ /+/g')
	url="$YOUTUBE_URL/$(curl -s "$INVIDIOUS_URL/search?q=$search" | grep -Eo "watch\?v=.{11}" | head -n 1)"
	"$player_fn" "$url"
}

download() {
	input
	search=$(echo "${query}" | sed 's/ /+/g')
	url="$YOUTUBE_URL/$(curl -s "$INVIDIOUS_URL/search?q=$search" | grep -Eo "watch\?v=.{11}" | head -n 1)"
	yt-dlp "$url"
}

select() {
	choice=$(menu | fzf | cut -d. -f1) || exit

	case $choice in
		1)
			download
			;;
		2)
			search_yt
			;;
		3)
			update_script
			;;
		*)
			inf "Program terminated" && exit 0
			;;
	esac
}
	
trap 'printf "\033[0m";[ -f "$logfile".new ] && rm "$logfile".new;exit 1' INT HUP

while getopts 'vq:dp:chDUVa:' OPT; do
	case $OPT in
		h)
			help_text
			exit 0
			;;
		v)
			player_fn="vlc"
			select
			;;
		U)
			update_script
			exit 0
			;;
		V)
			version_text
			exit 0
			;;
		c)
			select
			;;
		*)
			help_text
			exit 0
			;;
	esac
done
shift $((OPTIND - 1))

# Checks for the main dependencies
dep_ch "sed" "curl" "grep" "git" "yt-dlp" "fzf"
